# Generated by Django 5.2.1 on 2025-06-14 20:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=10)),
                ('comments', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('profile', models.FileField(max_length=200, upload_to='profile/')),
                ('user_type', models.CharField(default='user', max_length=5)),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('user_agent', models.CharField(max_length=300)),
                ('ip_address', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=300)),
                ('ip_address', models.CharField(max_length=300)),
                ('viewed_time', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.customers')),
            ],
        ),
    ]
