# Generated by Django 4.2.23 on 2025-06-26 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.FileField(max_length=200, upload_to='cover/')),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=10)),
                ('comments', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='customersdetail',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='click',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Customers',
        ),
        migrations.AddField(
            model_name='click',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='click',
            name='ip_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='CustomersDetail',
        ),
        migrations.AlterField(
            model_name='click',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
